/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    'IIc:roundChevronLeft': typeof import('~icons/ic/round-chevron-left')['default']
    'IIc:roundHome': typeof import('~icons/ic/round-home')['default']
    'ILineMd:githubTwotone': typeof import('~icons/line-md/github-twotone')['default']
    'ILineMd:moonFilledAltToSunnyFilledLoopTransition': typeof import('~icons/line-md/moon-filled-alt-to-sunny-filled-loop-transition')['default']
    'ILineMd:sunnyFilledLoopToMoonAltFilledLoopTransition': typeof import('~icons/line-md/sunny-filled-loop-to-moon-alt-filled-loop-transition')['default']
    NaiveProvider: typeof import('./../src/components/common/NaiveProvider.vue')['default']
    NaiveProviderContent: typeof import('./../src/components/common/NaiveProviderContent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VarAppBar: typeof import('@varlet/ui')['_AppBarComponent']
    VarBottomNavigation: typeof import('@varlet/ui')['_BottomNavigationComponent']
    VarBottomNavigationItem: typeof import('@varlet/ui')['_BottomNavigationItemComponent']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarCard: typeof import('@varlet/ui')['_CardComponent']
    VarResult: typeof import('@varlet/ui')['_ResultComponent']
    VarSkeleton: typeof import('@varlet/ui')['_SkeletonComponent']
    VarStyleProvider: typeof import('@varlet/ui')['_StyleProviderComponent']
  }
}
