/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    'IAntDesign:fullscreenExitOutlined': typeof import('~icons/ant-design/fullscreen-exit-outlined')['default']
    'IAntDesign:fullscreenOutlined': typeof import('~icons/ant-design/fullscreen-outlined')['default']
    'IIc:roundChevronLeft': typeof import('~icons/ic/round-chevron-left')['default']
    'IIc:roundHome': typeof import('~icons/ic/round-home')['default']
    'IIc:roundRefresh': typeof import('~icons/ic/round-refresh')['default']
    'ILineMd:githubLoop': typeof import('~icons/line-md/github-loop')['default']
    'ILineMd:githubTwotone': typeof import('~icons/line-md/github-twotone')['default']
    'ILineMd:moonAltToSunnyOutlineLoopTransition': typeof import('~icons/line-md/moon-alt-to-sunny-outline-loop-transition')['default']
    'ILineMd:moonFilledAltToSunnyFilledLoopTransition': typeof import('~icons/line-md/moon-filled-alt-to-sunny-filled-loop-transition')['default']
    'ILineMd:moonFilledToSunnyFilledLoopTransition': typeof import('~icons/line-md/moon-filled-to-sunny-filled-loop-transition')['default']
    'ILineMd:sunnyFilledLoopToMoonAltFilledLoopTransition': typeof import('~icons/line-md/sunny-filled-loop-to-moon-alt-filled-loop-transition')['default']
    'ILineMd:sunnyFilledToMoonFilledLoopTransition': typeof import('~icons/line-md/sunny-filled-to-moon-filled-loop-transition')['default']
    'ITabler:indentDecrease': typeof import('~icons/tabler/indent-decrease')['default']
    'ITabler:indentIncrease': typeof import('~icons/tabler/indent-increase')['default']
    NaiveProvider: typeof import('./../src/components/common/NaiveProvider.vue')['default']
    NaiveProviderContent: typeof import('./../src/components/common/NaiveProviderContent.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NGradientText: typeof import('naive-ui')['NGradientText']
    NH1: typeof import('naive-ui')['NH1']
    NH2: typeof import('naive-ui')['NH2']
    NIcon: typeof import('naive-ui')['NIcon']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NTooltip: typeof import('naive-ui')['NTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VarAppBar: typeof import('@varlet/ui')['_AppBarComponent']
    VarBottomNavigation: typeof import('@varlet/ui')['_BottomNavigationComponent']
    VarBottomNavigationItem: typeof import('@varlet/ui')['_BottomNavigationItemComponent']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarCard: typeof import('@varlet/ui')['_CardComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarResult: typeof import('@varlet/ui')['_ResultComponent']
    VarSkeleton: typeof import('@varlet/ui')['_SkeletonComponent']
    VarStyleProvider: typeof import('@varlet/ui')['_StyleProviderComponent']
    VarSwipe: typeof import('@varlet/ui')['_SwipeComponent']
    VarSwipeItem: typeof import('@varlet/ui')['_SwipeItemComponent']
  }
}
